### ISSUE TITLE
Ugly error when -m option is missing

### ISSUE THREAD

**Issue by cyberelfo** [globocom/khan#5]
If you forget the -m option in the command line the shell outputs the error below:

`Traceback (most recent call last):
  File "/Users/franklin/anaconda/bin/khan", line 11, in <module>
    sys.exit(main())
  File "/Users/franklin/anaconda/lib/python2.7/site-packages/khan/main.py", line 86, in main
    command_class = command_factory(parameters.method)
  File "/Users/franklin/anaconda/lib/python2.7/site-packages/khan/commands/__init__.py", line 13, in command_factory
    raise AttributeError('Unknown method: {}'.format(command_name))
`

**Comment by rdantassilva** [comment]
Issue fixed.
